{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cfi-fed
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cfi-fed.labels" . | nindent 4 }}
  {{- if .Values.ingress.rewrite }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: cfi-fed-tls
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ if .Values.ingress.rewrite }}/registry(/|$)(.*){{ else }}/registry{{ end }}
            pathType: {{ if .Values.ingress.rewrite }}ImplementationSpecific{{ else }}Prefix{{ end }}
            backend:
              service:
                name: cfi-registry
                port:
                  number: {{ .Values.registry.port }}
          - path: {{ if .Values.ingress.rewrite }}/coordinator(/|$)(.*){{ else }}/coordinator{{ end }}
            pathType: {{ if .Values.ingress.rewrite }}ImplementationSpecific{{ else }}Prefix{{ end }}
            backend:
              service:
                name: cfi-coordinator
                port:
                  number: {{ .Values.coordinator.port }}
          - path: {{ if .Values.ingress.rewrite }}/aggregator(/|$)(.*){{ else }}/aggregator{{ end }}
            pathType: {{ if .Values.ingress.rewrite }}ImplementationSpecific{{ else }}Prefix{{ end }}
            backend:
              service:
                name: cfi-aggregator
                port:
                  number: {{ .Values.aggregator.port }}
{{- end }}
